### ISSUE TITLE
community links.md no longer exists

### ISSUE THREAD

**Issue by ProjectEther** [BigfootsGS/BigfootsGS.github.io#29]
The community links part for alt links is no longer a thing. Would be nice if you bring this back

**Comment by Rockpods1** [comment]
The BGS team is currently finding who did this, it will be fixed ASAP

**Comment by Rockpods1** [comment]
This is now fixed, just click where the arrow is
![where the arrow is.](https://user-images.githubusercontent.com/90806701/192110277-316ba0dc-c31a-46ed-b729-b7e8aec0ef7a.png)
