### ISSUE TITLE
ruffle

### ISSUE THREAD

**Issue by Harlan124** [BigfootsGS/BigfootsGS.github.io#37]
### Description

ruffle says on all the flash games the ruffle emulator doesnt support action script and then the games dont work 

### Expected behavior

if u could fix that that would be nice

### Relevant Assets/Logs

s

**Comment by Bigfoot9999** [comment]
I am looking into it. Thanks for letting us know :)

**Comment by Harlan124** [comment]
now ruffle isnt even there and the flash games are stuck on loading

**Comment by Bigfoot9999** [comment]
We have fixed all the Flash Games @Harlan124
